language: node_js
node_js:
- 13.1.0
branches:
  only:
  - master
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: 140.143.191.101
before_install:
- openssl aes-256-cbc -K $encrypted_fc32dcfc7826_key -iv $encrypted_fc32dcfc7826_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
