language: node_js
node_js:
- 13.1.0
branches:
  only:
  - master
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: 140.143.191.101
before_install:
- openssl aes-256-cbc -K $encrypted_fc32dcfc7826_key -iv $encrypted_fc32dcfc7826_iv
  -in huahua-rsa.enc -out ~\/.ssh/huahua-rsa -d
- chmod 600 ~/.ssh/huahua-rsa

after_success:
  - ssh root@140.143.191.101 "cd /data/app && sh bootstrap.sh"