language: node_js
node_js:
- 10.0.0
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_fc32dcfc7826_key -iv $encrypted_fc32dcfc7826_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa